
export const categoriesData = [
  {
    slug: "pavers-hardscape",
    name: "Pavers & Hardscape",
    cover: "/assets/Day5/13.jpeg",
    images: [
      "/assets/gallery-pavers-CI-NuO7W.jpg",
      "/assets/Day5/13.jpeg",
      "/assets/Day1/1.jpeg",
      "/assets/Day1/2.jpeg",
      "/assets/Day1/3.jpeg",
      "/assets/Day1/4.jpeg",
      "/assets/Day1/5.jpeg",
      "/assets/Day1/6.jpeg",
      "/assets/Day1/7.jpeg",
      "/assets/Day1/8.jpeg",
      "/assets/Day1/9.jpeg",
      "/assets/Day1/10.jpeg",
      "/assets/Day1/11.jpeg",
      "/assets/Day1/12.jpeg",
      "/assets/Day1/13.jpeg",
      "/assets/Day1/14.jpeg",
      "/assets/Day1/15.jpeg",
      "/assets/Day1/16.jpeg",
      "/assets/Day1/17.jpeg",
      "/assets/Day1/18.jpeg",
      "/assets/Day1/19.jpeg",
      "/assets/Day1/20.jpeg",
      "/assets/Day1/21.jpeg",
      "/assets/Day1/22.jpeg",
      "/assets/Day1/23.jpeg",
      "/assets/Day1/24.jpeg",
    ]
  },
  {
    slug: "turf",
    name: "Turf",
    cover: "/assets/Day1/18.jpeg",
    images: [
      "/assets/Day1/18.jpeg",
      "/assets/Day2/project2.jpeg",
      "/assets/Day2/1.jpeg",
      "/assets/Day2/2.jpeg",
      "/assets/Day2/3.jpeg",
      "/assets/Day2/4.jpeg",
      "/assets/Day2/5.jpeg",
      "/assets/Day2/6.jpeg",
      "/assets/Day2/7.jpeg",
      "/assets/Day2/8.jpeg",
      "/assets/Day2/9.jpeg",
      "/assets/Day2/10.jpeg",
      "/assets/Day3/1.jpeg",
      "/assets/Day3/2.jpeg",
      "/assets/Day3/3.jpeg",
      "/assets/Day3/4.jpeg",
      "/assets/Day3/5.jpeg",
      "/assets/Day3/6.jpeg",
      "/assets/Day3/7.jpeg",
      "/assets/Day3/8.jpeg",
      "/assets/Day3/9.jpeg",
      "/assets/Day3/10.jpeg",
    ]
  },
  {
    slug: "lighting",
    name: "Lighting",
    cover: "/assets/Day1/project1.jpeg",
    images: [
      "/assets/Day1/project1.jpeg",
      "/assets/Day4/project4.jpeg",
      "/assets/Day4/1.jpeg",
      "/assets/Day4/2.jpeg",
      "/assets/Day4/3.jpeg",
      "/assets/Day4/4.jpeg",
      "/assets/Day4/5.jpeg",
      "/assets/Day4/6.jpeg",
      "/assets/Day4/7.jpeg",
      "/assets/Day4/8.jpeg",
      "/assets/Day4/9.jpeg",
      "/assets/Day4/10.jpeg",
      "/assets/Day4/11.jpeg",
      "/assets/Day4/12.jpeg",
      "/assets/Day4/13.jpeg",
      "/assets/Day4/14.jpeg",
      "/assets/Day4/15.jpeg",
      "/assets/Day4/16.jpeg",
      "/assets/Day4/17.jpeg",
      "/assets/Day4/18.jpeg",
      "/assets/Day4/19.jpeg",
      "/assets/Day4/20.jpeg",
    ]
  },
  {
    slug: "outdoor-features",
    name: "Outdoor Features",
    cover: "/assets/Day3/1.jpeg",
    images: [
      "/assets/Day3/1.jpeg",
      "/assets/Day5/project5.jpeg",
      "/assets/Day5/1.jpeg",
      "/assets/Day5/2.jpeg",
      "/assets/Day5/3.jpeg",
      "/assets/Day5/4.jpeg",
      "/assets/Day5/5.jpeg",
      "/assets/Day5/6.jpeg",
      "/assets/Day5/7.jpeg",
      "/assets/Day5/8.jpeg",
      "/assets/Day5/9.jpeg",
      "/assets/Day5/10.jpeg",
      "/assets/Day5/11.jpeg",
      "/assets/Day5/12.jpeg",
      "/assets/Day5/13.jpeg",
      "/assets/Day5/14.jpeg",
      "/assets/Day5/15.jpeg",
      "/assets/Day5/16.jpeg",
      "/assets/Day5/17.jpeg",
      "/assets/Day5/18.jpeg",
      "/assets/Day5/19.jpeg",
      "/assets/Day5/20.jpeg",
      "/assets/Day5/21.jpeg",
    ]
  },
  {
    slug: "top-view",
    name: "Top view",
    cover: "/assets/Day1/1.jpeg",
    images: [
      "/assets/Day1/1.jpeg",
      "/assets/Day6/project6.jpeg",
      "/assets/Day6/1.jpeg",
      "/assets/Day6/2.jpeg",
      "/assets/Day6/3.jpeg",
      "/assets/Day6/4.jpeg",
      "/assets/Day6/5.jpeg",
      "/assets/Day6/6.jpeg",
      "/assets/Day6/7.jpeg",
      "/assets/Day6/8.jpeg",
      "/assets/Day6/9.jpeg",
      "/assets/Day6/10.jpeg",
      "/assets/Day6/11.jpeg",
      "/assets/Day6/12.jpeg",
      "/assets/Day6/13.jpeg",
      "/assets/Day6/14.jpeg",
      "/assets/Day6/15.jpeg",
      "/assets/Day6/16.jpeg",
      "/assets/Day6/17.jpeg",
    ]
  },
];