const imagesDay1 = [
  "/assets/Day1/project1.jpeg",
  "/assets/Day1/1.jpeg",
  "/assets/Day1/2.jpeg",
  "/assets/Day1/3.jpeg",
  "/assets/Day1/4.jpeg",
  "/assets/Day1/5.jpeg",
  "/assets/Day1/6.jpeg",
  "/assets/Day1/7.jpeg",
  "/assets/Day1/8.jpeg",
  "/assets/Day1/9.jpeg",
  "/assets/Day1/10.jpeg",
  "/assets/Day1/11.jpeg",
  "/assets/Day1/12.jpeg",
  "/assets/Day1/13.jpeg",
  "/assets/Day1/14.jpeg",
  "/assets/Day1/15.jpeg",
  "/assets/Day1/16.jpeg",
  "/assets/Day1/17.jpeg",
  "/assets/Day1/18.jpeg",
  "/assets/Day1/19.jpeg",
  "/assets/Day1/20.jpeg",
  "/assets/Day1/21.jpeg",
  "/assets/Day1/22.jpeg",
  "/assets/Day1/23.jpeg",
  "/assets/Day1/24.jpeg",
];

const imagesDay2 = [
  "/assets/Day2/project2.jpeg",
  "/assets/Day2/1.jpeg",
  "/assets/Day2/2.jpeg",
  "/assets/Day2/3.jpeg",
  "/assets/Day2/4.jpeg",
  "/assets/Day2/5.jpeg",
  "/assets/Day2/6.jpeg",
  "/assets/Day2/7.jpeg",
  "/assets/Day2/8.jpeg",
  "/assets/Day2/9.jpeg",
  "/assets/Day2/10.jpeg",
];

const imagesDay3 = [
  "/assets/Day3/project3.jpeg",
  "/assets/Day3/1.jpeg",
  "/assets/Day3/2.jpeg",
  "/assets/Day3/3.jpeg",
  "/assets/Day3/4.jpeg",
  "/assets/Day3/5.jpeg",
  "/assets/Day3/6.jpeg",
  "/assets/Day3/7.jpeg",
  "/assets/Day3/8.jpeg",
  "/assets/Day3/9.jpeg",
  "/assets/Day3/10.jpeg",
  "/assets/Day3/11.jpeg",
  "/assets/Day3/12.jpeg",
  "/assets/Day3/13.jpeg",
  "/assets/Day3/14.jpeg",
  "/assets/Day3/15.jpeg",
  "/assets/Day3/16.jpeg",
  "/assets/Day3/17.jpeg",
  "/assets/Day3/18.jpeg",
  "/assets/Day3/19.jpeg",
  "/assets/Day3/20.jpeg",
  "/assets/Day3/21.jpeg",
  "/assets/Day3/22.jpeg",
];

const imagesDay4 = [
  "/assets/Day4/project4.jpeg",
  "/assets/Day4/1.jpeg",
  "/assets/Day4/2.jpeg",
  "/assets/Day4/3.jpeg",
  "/assets/Day4/4.jpeg",
  "/assets/Day4/5.jpeg",
  "/assets/Day4/6.jpeg",
  "/assets/Day4/7.jpeg",
  "/assets/Day4/8.jpeg",
  "/assets/Day4/9.jpeg",
  "/assets/Day4/10.jpeg",
  "/assets/Day4/11.jpeg",
  "/assets/Day4/12.jpeg",
  "/assets/Day4/13.jpeg",
  "/assets/Day4/14.jpeg",
  "/assets/Day4/15.jpeg",
  "/assets/Day4/16.jpeg",
  "/assets/Day4/17.jpeg",
  "/assets/Day4/18.jpeg",
  "/assets/Day4/19.jpeg",
  "/assets/Day4/20.jpeg",
  "/assets/Day4/21.jpeg",
  "/assets/Day4/22.jpeg",
  "/assets/Day4/23.jpeg",
  "/assets/Day4/24.jpeg",
  "/assets/Day4/25.jpeg",
  "/assets/Day4/26.jpeg",
  "/assets/Day4/27.jpeg",
  "/assets/Day4/28.jpeg",
];

const imagesDay5 = [
  "/assets/Day5/project5.jpeg",
  "/assets/Day5/1.jpeg",
  "/assets/Day5/2.jpeg",
  "/assets/Day5/3.jpeg",
  "/assets/Day5/4.jpeg",
  "/assets/Day5/5.jpeg",
  "/assets/Day5/6.jpeg",
  "/assets/Day5/7.jpeg",
  "/assets/Day5/8.jpeg",
  "/assets/Day5/9.jpeg",
  "/assets/Day5/10.jpeg",
  "/assets/Day5/11.jpeg",
  "/assets/Day5/12.jpeg",
  "/assets/Day5/13.jpeg",
  "/assets/Day5/14.jpeg",
  "/assets/Day5/15.jpeg",
  "/assets/Day5/16.jpeg",
  "/assets/Day5/17.jpeg",
  "/assets/Day5/18.jpeg",
  "/assets/Day5/19.jpeg",
  "/assets/Day5/20.jpeg",
  "/assets/Day5/21.jpeg",
];

const imagesDay6 = [
  "/assets/Day6/project6.jpeg",
  "/assets/Day6/1.jpeg",
  "/assets/Day6/2.jpeg",
  "/assets/Day6/3.jpeg",
  "/assets/Day6/4.jpeg",
  "/assets/Day6/5.jpeg",
  "/assets/Day6/6.jpeg",
  "/assets/Day6/7.jpeg",
  "/assets/Day6/8.jpeg",
  "/assets/Day6/9.jpeg",
  "/assets/Day6/10.jpeg",
  "/assets/Day6/11.jpeg",
  "/assets/Day6/12.jpeg",
  "/assets/Day6/13.jpeg",
  "/assets/Day6/14.jpeg",
  "/assets/Day6/15.jpeg",
  "/assets/Day6/16.jpeg",
];

const imagesDay7 = [
  "/assets/Day7/project7.jpeg",
  "/assets/Day7/1.jpeg",
  "/assets/Day7/2.jpeg",
  "/assets/Day7/3.jpeg",
  "/assets/Day7/4.jpeg",
  "/assets/Day7/5.jpeg",
  "/assets/Day7/6.jpeg",
  "/assets/Day7/7.jpeg",
  "/assets/Day7/8.jpeg",
  "/assets/Day7/9.jpeg",
  "/assets/Day7/10.jpeg",
  "/assets/Day7/11.jpeg",
  "/assets/Day7/12.jpeg",
  "/assets/Day7/13.jpeg",
  "/assets/Day7/14.jpeg",
  "/assets/Day7/15.jpeg",
  "/assets/Day7/16.jpeg",
  "/assets/Day7/17.jpeg",
  "/assets/Day7/18.jpeg",
  "/assets/Day7/19.jpeg",
  "/assets/Day7/20.jpeg",
  "/assets/Day7/21.jpeg",
];

// ──────────────────────────────────────────────
// Final exported data
// ──────────────────────────────────────────────

export const pastWorkData = [
  {
    slug: "past-project-1",
    projectno: "Project 1",
    name: "Fall 2024",
    coverImage: "/assets/Day1/project1.jpeg",
    images: imagesDay1,
  },
  {
    slug: "past-project-2",
    projectno: "Project 2",
    name: "Fall 2022",
    coverImage: "/assets/Day2/project2.jpeg",
    images: imagesDay2,
  },
  {
    slug: "past-project-3",
    projectno: "Project 3",
    name: "Spring 2025",
    coverImage: "/assets/Day3/project3.jpeg",
    images: imagesDay3,
  },
  {
    slug: "past-project-4",
    projectno: "Project 4",
    name: "Summer 2025",
    coverImage: "/assets/Day4/project4.jpeg",
    images: imagesDay4,
  },
  {
    slug: "past-project-5",
    projectno: "Project 5",
    name: "Fall 2025",
    coverImage: "/assets/Day5/project5.jpeg",
    images: imagesDay5,
  },
  {
    slug: "past-project-6",
    projectno: "Project 6",
    name: "Fall 2024",
    coverImage: "/assets/Day6/project6.jpeg",
    images: imagesDay6,
  },
  {
    slug: "past-project-7",
    projectno: "Project 7",
    name: "Fall 2024",
    coverImage: "/assets/Day7/project7.jpeg",
    images: imagesDay7,
  },
];